### ISSUE TITLE
Simulation type setup submenu

### ISSUE THREAD

**Issue by besharat1986** [FSillT/QCADesigner-E#1]
In QCA designer-E, Windows version:
When I click on the "Simulation type setup" submenu, the software automatically closes and does not allow defining variables. Please guide me in solving this problem.

Best regards

**Comment by FSillT** [comment]
This option is, indeed, unused. All simulation parameters are setup via "Simulation Engine Setup"

**Comment by besharat1986** [comment]
Dear Frank

Thank you for your email

In the QCA designer-E, if the variables are not defined, the simulation
results and energy consumption will be different in every simulation.
Please advise me.

Best wishes

**Comment by FSillT** [comment]
Which variables do you mean? I recommend, to use the provided test structures and standard options for initial tests.
