### ISSUE TITLE
why does qca designer-e ,windows version ,get closed ,when I click on "simulation type setup" submenu?

### ISSUE THREAD

**Issue by ghodratollah** [FSillT/QCADesigner-E#2]
Hello, everyone 
I have a problem with  **QCA Designer-E**, windows version 
When I click on "simulation type setup" submenu, the software gets closed.
I would be grateful  if anyone could help me.

**Comment by FSillT** [comment]
This option is, indeed, unused. All simulation parameters are setup via "Simulation Engine Setup".

**Comment by ghodratollah** [comment]
Hello
I send you a video  about the results  of my design in  two  different
software(QCA & QCA-E),It is obvious that results are different.
Please consider and advise me?
best regards.https://www.namasha.com/v/cd9yshYI

**Comment by FSillT** [comment]
Hi,
can you, please, provide me your circuit and a short overview of your steps?
Thank you
Frank

**Comment by ghodratollah** [comment]
Hi ,
I will reply as soon as possible

**Comment by ghodratollah** [comment]
Dear Frank

thank you for email

I have accomplished the following steps for my design.

In the QCA Designer software.

1- a three-bit counter circuit with 110 cells were designed in the QCA
designer software.

2- For simulation, simulation > simulation type setup>" The vector table
setup" submenu. I defined the 47 variables.

3- the coherence vector engine has been chosen.

4- start simulation submenu.

5- I saw simulation results.

In the QCA Designer-E software.

1- I loaded my circuit.

2- Simulation > Simulation Engine Setup… and select Coherence Vector (w/
Energy)



3- start simulation submenu.

4- I saw simulation result.

The waveforms are different in both software.

The amount of energy consumption calculation is also different in each
simulation time.

All the steps mentioned in the video are available. Please watch the video
to the end if possible and advise me.

thanks.

**Comment by FSillT** [comment]
Which engine did you choose in QCA-Designer? It must be coherence vector, else results might differ.
How did you define the inputs in QCA-Designer-E? Where can I find the circuit?

Cheers

**Comment by ghodratollah** [comment]
My circuit attached in previous email,i choose coherence vector eng in QCA
Designer,i cant defined input in QCA Designer -E
Thanks

در تاریخ دوشنبه ۱۲ سپتامبر ۲۰۲۲،‏ ۱۵:۲۹ Frank Sill Torres <
***@***.***> نوشت:

**Comment by ghodratollah** [comment]
HI

**Comment by FSillT** [comment]
Hi,

I can't the the attachment in github. 
In QCADesigner-E, all simulations are with coherence vector.

**Comment by ghodratollah** [comment]
Hi
Please give me another email address ,i send attachment to it.
thanks

در تاریخ دوشنبه ۱۲ سپتامبر ۲۰۲۲،‏ ۲۱:۰۵ Frank Sill Torres <
***@***.***> نوشت:

**Comment by ghodratollah** [comment]
[](url)https://s24.picofile.com/file/8453088718/Energy_Dissipation_in_eV.pdf.html

**Comment by ghodratollah** [comment]
[](url)https://s24.picofile.com/file/8453088742/coherence_vector_asadi_The_new_structure_of_three_bits_counter_with_110_cells.qca.html

**Comment by FSillT** [comment]
Hi,

where do I click do download the file?

**Comment by ghodratollah** [comment]
https://drive.google.com/file/d/1kS8C3cWUtF1zkKu_M_fSnJZlOrdMc-WD/view?usp=drivesdk

در تاریخ سه‌شنبه ۱۳ سپتامبر ۲۰۲۲،‏ ۸:۱۵ ghodrat asadi <
***@***.***> نوشت:

**Comment by ghodratollah** [comment]
https://drive.google.com/file/d/1ecatQdmxfa1OS-lsgy8uvAC3ENtw83by/view?usp=drivesdk

در تاریخ سه‌شنبه ۱۳ سپتامبر ۲۰۲۲،‏ ۱۳:۱۹ ghodrat asadi <
***@***.***> نوشت:

**Comment by FSillT** [comment]
Hi,

thank you for the files. 
There are actually two issues:

1) We didn't implement the bus option in the QCAD-E. When you stored your file in QCAD, this option was added to the .cir-file. You can open the *.cir and check the last section between [TYPE:BUS_LAYOUT] and [#TYPE:BUS_LAYOUT]. You must remove that section, when simulating in QCAD-E.

2) you placed neighboring cells with clock zones that differ by more than one, e.g. cells with clock3 next to clock1, missing clock0. Such structures have a random behavior, as you see in the obtained energy results. Though, the stable result might be correct, but you should be able to justify the use of such structures.
